plugins {
    id 'com.android.application'
}

android {
    namespace 'com.divar.pricemeter'
    compileSdk 35

    defaultConfig {
        applicationId 'com.divar.pricemeter.v8'
        minSdk 23
        targetSdk 35
        versionCode 8
        versionName '8.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
