plugins {
    id 'com.android.application'
}

android {
    namespace 'com.divar.pricemeter'
    compileSdk 35

    defaultConfig {
        applicationId 'com.divar.pricemeter.v11'
        minSdk 23
        targetSdk 35
        versionCode 11
        versionName '11.0'
    }

    signingConfigs {
        release {
            storeFile file('../release-key.jks')
            storePassword System.getenv('RELEASE_STORE_PASSWORD')
            keyAlias 'divar'
            keyPassword System.getenv('RELEASE_KEY_PASSWORD')
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
