plugins {
    id 'com.android.application'
}

android {
    namespace 'com.divar.pricemeter'
    compileSdk 35

    defaultConfig {
        applicationId 'com.divar.pricemeter.v5'
        minSdk 23
        targetSdk 35
        versionCode 5
        versionName '5.0'
    }

    signingConfigs {
        release {
            storeFile file('../divar-release.keystore')
            storePassword System.getenv('KEYSTORE_PASSWORD') ?: ''
            keyAlias 'divar'
            keyPassword System.getenv('KEYSTORE_PASSWORD') ?: ''
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}
