package com.divar.pricemeter;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.text.NumberFormat;
import java.util.*;
import java.util.regex.*;
import java.util.zip.*;

public class MainActivity extends Activity {
    EditText city,area,minSqm,maxSqm,minPsm,maxPsm; Spinner category; TextView summary,results; WebView web,detailWeb;
    ArrayList<Listing> rows=new ArrayList<>(); ArrayList<String> links=new ArrayList<>(); int detailIndex=0; boolean running=false;
    final String[] cats={"buy-apartment","rent-apartment","buy-house-villa"}; final NumberFormat nf=NumberFormat.getIntegerInstance(Locale.US);
    static class Listing{
        String title="",link="",price="",deposit="",rent="",sqm="",rooms="",floor="",totalFloors="",buildYear="",parking="",elevator="",storage="",pricePerSqm="",address="",postedDate="",updatedDate="",ladder="",type="",agency="",description="";
        String[] row(){return new String[]{title,price,sqm,rooms,floor,pricePerSqm,address,postedDate,updatedDate,ladder,parking,elevator,storage,totalFloors,buildYear,deposit,rent,type,agency,description,link};}
    }
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    TextView label(String s){TextView t=new TextView(this);t.setText(s);t.setTextSize(14);t.setTextColor(Color.rgb(70,70,70));t.setPadding(dp(4),dp(7),dp(4),dp(2));return t;}
    EditText field(String h,String v){EditText e=new EditText(this);e.setHint(h);e.setText(v);e.setTextSize(15);e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);e.setBackground(bg(Color.WHITE,14));return e;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackground(bg(Color.rgb(45,125,95),18));return b;}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(25,35,30));
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,247,246));root.setPadding(dp(14),dp(42),dp(14),dp(10));
        TextView title=new TextView(this);title.setText("تحلیل قیمت دیوار");title.setTextSize(23);title.setTextColor(Color.WHITE);title.setGravity(Gravity.CENTER);title.setTypeface(null,1);title.setBackground(bg(Color.rgb(32,75,57),18));root.addView(title,new LinearLayout.LayoutParams(-1,dp(58)));
        ScrollView sv=new ScrollView(this);LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(0,dp(10),0,dp(8));
        city=field("شهر","tabriz");area=field("محله","نصر");f.addView(label("شهر"));f.addView(city,new LinearLayout.LayoutParams(-1,dp(50)));f.addView(label("محله"));f.addView(area,new LinearLayout.LayoutParams(-1,dp(50)));
        f.addView(label("نوع آگهی"));category=new Spinner(this);category.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,cats));category.setBackground(bg(Color.WHITE,14));f.addView(category,new LinearLayout.LayoutParams(-1,dp(50)));
        LinearLayout r1=new LinearLayout(this);r1.setOrientation(LinearLayout.HORIZONTAL);minSqm=field("حداقل متر","100");maxSqm=field("حداکثر متر","400");r1.addView(minSqm,new LinearLayout.LayoutParams(0,dp(50),1));r1.addView(new Space(this),new LinearLayout.LayoutParams(dp(8),1));r1.addView(maxSqm,new LinearLayout.LayoutParams(0,dp(50),1));f.addView(label("محدوده متراژ"));f.addView(r1);
        LinearLayout r2=new LinearLayout(this);r2.setOrientation(LinearLayout.HORIZONTAL);minPsm=field("حداقل قیمت/متر","10000000");maxPsm=field("حداکثر قیمت/متر","100000000");r2.addView(minPsm,new LinearLayout.LayoutParams(0,dp(50),1));r2.addView(new Space(this),new LinearLayout.LayoutParams(dp(8),1));r2.addView(maxPsm,new LinearLayout.LayoutParams(0,dp(50),1));f.addView(label("محدوده قیمت هر متر (تومان)"));f.addView(r2);
        Button search=button("🔎  جستجو و تحلیل آگهی‌ها");search.setOnClickListener(v->loadDivar());f.addView(search,new LinearLayout.LayoutParams(-1,dp(54)));
        summary=new TextView(this);summary.setText("آماده جستجو");summary.setTextSize(15);summary.setTextColor(Color.rgb(45,70,58));summary.setGravity(Gravity.CENTER);summary.setPadding(dp(8),dp(12),dp(8),dp(12));f.addView(summary);
        Button export=button("📊  خروجی Excel با ستون‌های قابل فیلتر");export.setOnClickListener(v->exportXlsx());f.addView(export,new LinearLayout.LayoutParams(-1,dp(54)));sv.addView(f);root.addView(sv,new LinearLayout.LayoutParams(-1,0,.43f));
        results=new TextView(this);results.setTextSize(14);results.setTextColor(Color.DKGRAY);results.setPadding(dp(8),dp(8),dp(8),dp(8));ScrollView rs=new ScrollView(this);rs.setBackground(bg(Color.WHITE,16));rs.addView(results);root.addView(rs,new LinearLayout.LayoutParams(-1,0,.24f));
        web=makeWeb();root.addView(web,new LinearLayout.LayoutParams(-1,0,.33f));detailWeb=makeWeb();detailWeb.setVisibility(View.INVISIBLE);root.addView(detailWeb,new LinearLayout.LayoutParams(1,1));setContentView(root);
    }
    WebView makeWeb(){WebView w=new WebView(this);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setUserAgentString("Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 Chrome/125 Mobile Safari/537.36");w.setWebViewClient(new WebViewClient());return w;}
    String norm(String s){if(s==null)return "";StringBuilder b=new StringBuilder();for(char c:s.toCharArray()){if(c>='۰'&&c<='۹')b.append((char)('0'+c-'۰'));else if(c>='٠'&&c<='٩')b.append((char)('0'+c-'٠'));else b.append(c);}return b.toString().replace('\u200c',' ').replaceAll("[ \\t]+"," ").trim();}
    double num(String s){try{return Double.parseDouble(norm(s).replace(",","").replace("٬","").replace(" ",""));}catch(Exception e){return 0;}} String fmt(double x){return nf.format(Math.round(x));}
    String amount(String s){if(s==null)return "";Matcher m=Pattern.compile("([0-9][0-9,٬. ]{0,30})\\s*(میلیارد|میلیون|هزار)?").matcher(norm(s));if(!m.find())return "";double v=num(m.group(1));String u=m.group(2);if("میلیارد".equals(u))v*=1e9;else if("میلیون".equals(u))v*=1e6;else if("هزار".equals(u))v*=1e3;return v>0?fmt(v):"";}
    String near(String t,String labels){Matcher m=Pattern.compile("(?i)(?:"+labels+")\\s*[:：\\-]?\\s*([^\\n]{1,180})").matcher(norm(t));return m.find()?m.group(1).trim():"";} String nearAmount(String t,String labels){String x=near(t,labels);return x.isEmpty()?"":amount(x);}
    String area(String t){Matcher m=Pattern.compile("(?<![0-9])([0-9]{2,4})\\s*(?:متر(?:مربع)?|m²|m2)").matcher(norm(t));return m.find()?m.group(1):"";} String rooms(String t){Matcher m=Pattern.compile("([0-9]{1,2})\\s*(?:خوابه?|خواب|اتاق)").matcher(norm(t));return m.find()?m.group(1):"";} String floor(String t){Matcher m=Pattern.compile("(?:طبقه|واحد)\\s*[:：\\-]?\\s*(همکف|زیرزمین|منفی\\s*[0-9]+|[0-9]+)").matcher(norm(t));return m.find()?m.group(1):"";}
    String feature(String t,String f){return norm(t).contains(f)?"دارد":"";} String desc(String t){String x=near(t,"توضیحات|شرح");return x.isEmpty()?(t.length()>1800?t.substring(0,1800):t):x;}
    void loadDivar(){String c=city.getText().toString().trim(),a=area.getText().toString().trim(),cat=cats[category.getSelectedItemPosition()];String url="https://divar.ir/s/"+Uri.encode(c)+"/"+cat+(a.isEmpty()?"":"?q="+Uri.encode(a));rows.clear();links.clear();detailIndex=0;running=false;summary.setText("در حال بارگذاری دیوار…");results.setText("");web.loadUrl(url);web.postDelayed(()->collect(0),6500);}
    void collect(int n){if(n>=14){parseSearch();return;}web.evaluateJavascript("window.scrollTo(0,document.body.scrollHeight);",x->web.postDelayed(()->collect(n+1),550));}
    void parseSearch(){String js="(function(){let a=[...document.querySelectorAll('a')].map(x=>x.href||'').filter(x=>x.includes('/v/'));return JSON.stringify([...new Set(a)].slice(0,40));})()";web.evaluateJavascript(js,val->{String s=unquote(val);Matcher m=Pattern.compile("https://divar\\.ir/v/[^\\\"\\s\\]]+").matcher(s);while(m.find()&&links.size()<40)if(!links.contains(m.group()))links.add(m.group());if(links.isEmpty()){summary.setText("آگهی‌ها نمایش داده شدند ولی لینک جزئیات استخراج نشد؛ احتمالاً دیوار ساختار صفحه را تغییر داده یا ضدربات فعال است.");return;}summary.setText("تعداد "+links.size()+" آگهی پیدا شد؛ دریافت جزئیات شروع شد…");running=true;processNext();});}
    String unquote(String s){if(s==null)return "";if(s.startsWith("\"")&&s.endsWith("\""))s=s.substring(1,s.length()-1);return s.replace("\\\"","\"").replace("\\/","/").replace("\\n","\n").replace("\\u003C","<").replace("\\u003E",">");}
    void processNext(){if(!running)return;if(detailIndex>=links.size()){running=false;showResults();return;}final int i=detailIndex;detailWeb.loadUrl(links.get(i));detailWeb.postDelayed(()->extract(i),3500);}
    void extract(int i){String js="(function(){return JSON.stringify({t:(document.querySelector('h1')||{}).innerText||'',b:document.body?document.body.innerText:''});})()";detailWeb.evaluateJavascript(js,val->{try{String raw=unquote(val);int p=raw.indexOf("\",\"b\":\"");String t="",b=raw;if(p>0){t=raw.substring(0,p).replace("{\"t\":\"","");b=raw.substring(p+7);if(b.endsWith("\"}"))b=b.substring(0,b.length()-2);}rows.add(parse(links.get(i),t,b));}catch(Exception e){Listing l=new Listing();l.link=links.get(i);rows.add(l);}detailIndex++;summary.setText("در حال دریافت جزئیات: "+detailIndex+" / "+links.size());processNext();});}
    Listing parse(String link,String title,String text){Listing l=new Listing();l.link=link;l.title=norm(title);l.sqm=area(text);l.rooms=rooms(text);l.floor=floor(text);l.price=nearAmount(text,"قیمت\\s*(?:کل|فروش)?|قیمت فروش");l.deposit=nearAmount(text,"ودیعه|رهن|پیش");l.rent=nearAmount(text,"اجاره|اجاره ماهانه");l.pricePerSqm=nearAmount(text,"قیمت\\s*/\\s*متر|قیمت هر متر|هر متر");if(l.pricePerSqm.isEmpty()&&num(l.sqm)>0&&num(l.price)>0)l.pricePerSqm=fmt(num(l.price)/num(l.sqm));l.address=near(text,"آدرس|موقعیت|محله|نشانی");l.postedDate=near(text,"تاریخ آگهی|زمان آگهی|منتشر شده|انتشار");l.updatedDate=near(text,"آخرین بروزرسانی|آخرین به‌روزرسانی|بروزرسانی|به‌روزرسانی");l.ladder=near(text,"نردبان|ویژه|ارتقا|فوری");l.parking=feature(text,"پارکینگ");l.elevator=feature(text,"آسانسور");l.storage=feature(text,"انباری");l.totalFloors=near(text,"تعداد طبقات|کل طبقات");l.buildYear=near(text,"سال ساخت|ساخت|بنا");l.type=near(text,"نوع ملک|نوع");l.agency=near(text,"مشاور|آژانس|املاک");l.description=desc(text);return l;}
    void showResults(){double sum=0,min=Double.MAX_VALUE,max=0;int n=0;StringBuilder s=new StringBuilder();for(Listing l:rows){double p=num(l.pricePerSqm);if(p>0){sum+=p;n++;min=Math.min(min,p);max=Math.max(max,p);}if(s.length()<9000)s.append(l.title).append("\n").append("قیمت: ").append(l.price).append(" | ").append(l.sqm).append(" متر | هر متر: ").append(l.pricePerSqm).append("\n\n");}summary.setText(n>0?"میانگین هر متر: "+fmt(sum/n)+" تومان | کمینه: "+fmt(min)+" | بیشینه: "+fmt(max):"تعداد آگهی: "+rows.size());results.setText(s.toString());}
    void exportXlsx(){if(rows.isEmpty()){Toast.makeText(this,"ابتدا جستجو و تحلیل را انجام دهید",Toast.LENGTH_LONG).show();return;}Intent in=new Intent(Intent.ACTION_CREATE_DOCUMENT);in.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");in.putExtra(Intent.EXTRA_TITLE,"DivarPriceAnalysis.xlsx");startActivityForResult(in,91);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==91&&c==RESULT_OK&&d!=null){try{OutputStream o=getContentResolver().openOutputStream(d.getData());writeXlsx(o);o.close();Toast.makeText(this,"فایل Excel با موفقیت ذخیره شد",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"خطا در ذخیره Excel",Toast.LENGTH_LONG).show();}}}
    String esc(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
    void writeXlsx(OutputStream out)throws Exception{ZipOutputStream z=new ZipOutputStream(out);String[][] data=new String[rows.size()+1][];data[0]=new String[]{"عنوان","قیمت","متراژ","تعداد خواب","طبقه","قیمت هر متر","آدرس","تاریخ آگهی","تاریخ بروزرسانی","نردبان","پارکینگ","آسانسور","انباری","تعداد طبقات","سال ساخت","ودیعه","اجاره","نوع ملک","مشاور/آژانس","توضیحات","لینک"};for(int i=0;i<rows.size();i++)data[i+1]=rows.get(i).row();StringBuilder sh=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");for(int r=0;r<data.length;r++){sh.append("<row r=\"").append(r+1).append("\">");for(int c=0;c<data[r].length;c++){sh.append("<c r=\"").append(cell(c,r)).append("\" t=\"inlineStr\"><is><t xml:space=\"preserve\">").append(esc(data[r][c])).append("</t></is></c>");}sh.append("</row>");}sh.append("</sheetData></worksheet>");put(z,"[Content_Types].xml","<?xml version=\"1.0\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");put(z,"_rels/.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");put(z,"xl/workbook.xml","<?xml version=\"1.0\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Listings\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");put(z,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");put(z,"xl/worksheets/sheet1.xml",sh.toString());z.close();}
    String cell(int c,int r){String x="";c++;while(c>0){int q=(c-1)%26;x=(char)('A'+q)+x;c=(c-1)/26;}return x+(r+1);} void put(ZipOutputStream z,String n,String s)throws Exception{z.putNextEntry(new ZipEntry(n));z.write(s.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
}
